# Tools defined here install into $XDG_STATE_HOME/dws/bin and are cached in
# $XDG_CACHE_HOME/dws/tools. Uncomment the entries you want to provision as part
# of this profile.
#
# An entry applies on every machine unless you specify filters:
#   platform = ["macos", "linux", "linux-ubuntu"]  # matches current OS/distro
#   hosts = ["work-laptop"]                          # matches sanitized hostname
#
# When multiple files define the same tool, the higher-precedence file replaces
# the entire entry. Workspace overrides live in $XDG_CONFIG_HOME/dws/config.toml.

# [tools.ripgrep]
# installer = "github"
# project = "BurntSushi/ripgrep"
# version = "v14.0.0"  # Optional pin
# asset_filter = ["^ripgrep-14\\.0\\.0-x86_64-apple-darwin\\.tar\\.gz$"]
# checksum = "sha256:0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
# platform = ["macos"]
#
# [[tools.ripgrep.bin]]
# source = "rg"
#
# [[tools.ripgrep.extras]]
# source = "doc/rg.1"
# kind = "man"
#
# [[tools.ripgrep.extras]]
# source = "complete/_rg"
# kind = "completion"
# shell = "zsh"

# [tools.uv]
# installer = "script"
# url = "https://astral.sh/uv/install.sh"
# shell = "sh"
# version = "latest"
# checksum = "sha256:cafecafecafecafecafecafecafecafecafecafecafecafecafecafecafecafe"
# self_update = true
#
# [[tools.uv.bin]]
# source = "uv"

# [tools.helix]
# installer = "github"
# project = "helix-editor/helix"
# asset_filter = ["^helix-.*-x86_64-linux\\.tar\\.xz$"]
# checksum = "sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
#
# [[tools.helix.bin]]
# source = "hx"
#
# [[tools.helix.extras]]
# source = "contrib/runtime/queries"
# kind = "other"
# target = "${XDG_DATA_HOME}/dws/helix/queries"

# [tools.gh]
# installer = "github"
# project = "cli/cli"
# asset_filter = ["^gh_.*_macOS_amd64\\.tar\\.gz$"]
# checksum = "sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
#
# [[tools.gh.bin]]
# source = "bin/gh"
