# macOS-specific applications layered on top of tools.toml.
#
# Entries here apply only on macOS machines.

# [ghostty]
# installer = "dmg"
# url = "https://ghostty.org/download"
# app = "Ghostty.app"
# team_id = "24VZTF6M5V"
# self_update = true
